# Generated by Django 4.2.19 on 2025-03-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_category_menu_ingredients_menu_name_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
